### PR TITLE
pkg: rename existing ubuntu-esm-precise.list file to trusty

### PR DESCRIPTION
**Pull request by blackboxsw**
When upgrading from precise to trusty and esm is enabled,
ubuntu-advantage-tools v 10ubuntu0.14.04.4 does not rename
any apt precise apt sources files to trusty.

So if customers have already upgraded from precise enabled-esm to trusty
10ubuntu0.14.04.4, a subsequent upgrade to version 19.6 will
skip trying to rename:
ubuntu-esm-precise.list -> ubuntu-esm-infra-trusty.list.

postinst unconditionally renames ubuntu-esm-precise.list to
ubuntu-esm-infra-trusty.list. It no longer limits this rename
operation to the case where postinst is upgrading from version 1 (the precise
package version)

Fixes: #899

### CODE REVIEW

**Comment by panlinux** [comment]
I'll build this and put it in a testing ppa

**Comment by panlinux** [comment]
So I did a test with this package: precise + esm -> do-release-upgade to trusty (with esm-trusty considered in the upgrade) -> ppa. As far as I can tell this worked. Let's see some diffs

a) what changed when upgrading to the PPA package.
Contents:
```diff
diff -uNr before-upgrade-to-ppa/apt/apt.conf.d/20apt-esm-hook.conf after-upgrade-to-ppa/apt/apt.conf.d/20apt-esm-hook.conf
--- before-upgrade-to-ppa/apt/apt.conf.d/20apt-esm-hook.conf    1970-01-01 00:00:00.000000000 +0000
+++ after-upgrade-to-ppa/apt/apt.conf.d/20apt-esm-hook.conf 2019-10-30 13:12:52.000000000 +0000
@@ -0,0 +1,7 @@
+APT::Update::Post-Invoke-Stats {
+   "[ ! -f /usr/lib/ubuntu-advantage/apt-esm-hook ] || /usr/lib/ubuntu-advantage/apt-esm-hook";
+};
+
+APT::Install::Post-Invoke-Success {
+   "[ ! -f /usr/lib/ubuntu-advantage/apt-esm-hook ] || /usr/lib/ubuntu-advantage/apt-esm-hook";
+}; 
diff -uNr before-upgrade-to-ppa/apt/apt.conf.d/51ubuntu-advantage-esm after-upgrade-to-ppa/apt/apt.conf.d/51ubuntu-advantage-esm
--- before-upgrade-to-ppa/apt/apt.conf.d/51ubuntu-advantage-esm 2019-08-27 20:34:45.000000000 +0000
+++ after-upgrade-to-ppa/apt/apt.conf.d/51ubuntu-advantage-esm  2019-10-25 14:32:06.000000000 +0000
@@ -1,3 +1,3 @@
 Unattended-Upgrade::Allowed-Origins {
-  "${distro_id}ESM:${distro_codename}-security";
+  "${distro_id}ESM:${distro_codename}-infra-security";
 };
diff -uNr before-upgrade-to-ppa/apt/sources.list.d/ubuntu-esm-infra-trusty.list after-upgrade-to-ppa/apt/sources.list.d/ubuntu-esm-infra-trusty.list
--- before-upgrade-to-ppa/apt/sources.list.d/ubuntu-esm-infra-trusty.list   1970-01-01 00:00:00.000000000 +0000
+++ after-upgrade-to-ppa/apt/sources.list.d/ubuntu-esm-infra-trusty.list    2019-10-30 14:01:25.753423017 +0000
@@ -0,0 +1,3 @@
+deb https://lol:secret@esm.ubuntu.com/ubuntu trusty-updates main
+# deb-src https://lol:secret@esm.ubuntu.com/ubuntu precise main
+deb https://canonical-sts:fiephaeghohvaesa5Xel@esm.ubuntu.com/ubuntu trusty-security main
diff -uNr before-upgrade-to-ppa/apt/sources.list.d/ubuntu-esm-precise.list after-upgrade-to-ppa/apt/sources.list.d/ubuntu-esm-precise.list
--- before-upgrade-to-ppa/apt/sources.list.d/ubuntu-esm-precise.list    2019-10-30 14:01:25.753423017 +0000
+++ after-upgrade-to-ppa/apt/sources.list.d/ubuntu-esm-precise.list 1970-01-01 00:00:00.000000000 +0000
@@ -1,3 +0,0 @@
-deb https://lol:secret@esm.ubuntu.com/ubuntu trusty-updates main
-# deb-src https://lol:secret@esm.ubuntu.com/ubuntu precise main
-deb https://lol:secret@esm.ubuntu.com/ubuntu trusty-security main
Binary files before-upgrade-to-ppa/apt/trusted.gpg.d/ubuntu-advantage-esm-infra-trusty.gpg and after-upgrade-to-ppa/apt/trusted.gpg.d/ubuntu-advantage-esm-infra-trusty.gpg differ
Binary files before-upgrade-to-ppa/apt/trusted.gpg.d/ubuntu-esm-keyring.gpg and after-upgrade-to-ppa/apt/trusted.gpg.d/ubuntu-esm-keyring.gpg differ
Binary files before-upgrade-to-ppa/apt/trusted.gpg.d/ubuntu-esm-v2-keyring.gpg and after-upgrade-to-ppa/apt/trusted.gpg.d/ubuntu-esm-v2-keyring.gpg differ
```
File listing:
```diff
--- before-upgrade-to-ppa.list	2019-10-30 14:21:58.360449118 +0000
+++ after-upgrade-to-ppa.list	2019-10-30 14:22:08.192308936 +0000
@@ -5,6 +5,7 @@
 /apt/apt.conf.d/05aptitude
 /apt/apt.conf.d/10periodic
 /apt/apt.conf.d/15update-stamp
+/apt/apt.conf.d/20apt-esm-hook.conf
 /apt/apt.conf.d/20archive
 /apt/apt.conf.d/20changelog
 /apt/apt.conf.d/50unattended-upgrades
@@ -19,7 +20,7 @@
 /apt/sources.list.d
 /apt/sources.list.d/ahasenack-ua-temp-trusty.list
 /apt/sources.list.distUpgrade
-/apt/sources.list.d/ubuntu-esm-precise.list
+/apt/sources.list.d/ubuntu-esm-infra-trusty.list
 /apt/sources.list.d/ubuntu-esm-precise.list.distUpgrade
 /apt/sources.list.d/ubuntu-esm-precise.list.save
 /apt/sources.list.save
@@ -27,5 +28,4 @@
 /apt/trusted.gpg.d
 /apt/trusted.gpg.d/ahasenack-ua-temp.gpg
 /apt/trusted.gpg.d/ahasenack-ua-temp.gpg~
-/apt/trusted.gpg.d/ubuntu-esm-keyring.gpg
-/apt/trusted.gpg.d/ubuntu-esm-v2-keyring.gpg
+/apt/trusted.gpg.d/ubuntu-advantage-esm-infra-trusty.gpg
```

**Comment by panlinux** [comment]
Next, testing a release upgrade with "proposed" (this ppa) enabled, so we don't go through the current trusty package.

**Comment by blackboxsw** [comment]
test script I was using to validate behavior
export LEGACY_TOKEN="<legacyToken>"

echo "Launch precise container with allowing ssh access for <LP_ID>"
cat >precise.yaml <<EOF
#cloud-config
ssh_import_id: [chad.smith]
EOF
lxc launch ubuntu-daily:precise sru-precise -c user.user-data="$(cat precise.yaml)"
while ! [ "N 2" = "$RUNLEVEL" ]; do echo -n '.'; sleep 1; RUNLEVEL=`lxc exec sru-precise runlevel`; done; echo


cat > ppa-key << EOF
-----BEGIN PGP PUBLIC KEY BLOCK-----

xo0EUTu+/gEEAMFpxLtgmZO7TzYhegd9bfkxNVO+panvC7YcEoaZliBS6u/r4maW
zJxCMzDB/OtokjQqRBdADu4WhnxHKiVan9gghlvtnX17anDdn+S9Hp06S9LMXBCP
xGD6pjPGjKUe7RiL/iD4YSAkw1QKjyKD+o3pAxKYVoQHbGyN5iJgUsNxABEBAAHN
HExhdW5jaHBhZCBQUEEgZm9yIENoYWQgU21pdGjCuAQTAQIAIgUCUTu+/gIbAwYL
CQgHAwIGFQgCCQoLBBYCAwECHgECF4AACgkQg3ErePW2/VcymAQAhzrazNOfqxo7
OURDB8nzrdxzgLal900UWXH+Vldhb1sgG8TrImcsIN5EyY0yvMNdwcl1L4vBRN09
nkr30LVNjGIASe3PWYABLNhrcxpV5ASyvP62YrhuZW4ZF9tY/3nQpL6SeO3rvKf4
0unSJDqyLC02XS+zL/76sW8vfqdPeRU=
=iz1N
-----END PGP PUBLIC KEY BLOCK-----
EOF

# emit script to upgrade u-a-t
cat > add_uat_apt_pocket.sh << EOF
#/bin/bash
pocket_name=\$1
if [ "\$pocket_name" = "devel" ]; then
  echo deb [trusted=yes] http://ppa.launchpad.net/chad.smith/junkyard/ubuntu trusty main | tee /etc/apt/sources.list.d/\$pocket_name.list
  apt-key add /ppa-key
else
  echo deb $ARCHIVE_URL \$pocket_name main | tee /etc/apt/sources.list.d/\$pocket_name.list
fi
EOF

lxc file push ppa-key sru-precise/
lxc file push add_uat_apt_pocket.sh sru-precise/
lxc exec sru-precise chmod 755 /add_uat_apt_pocket.sh

lxc snapshot sru-precise sru-precise-pristine

echo "Enable esm on precise"
lxc exec sru-precise ubuntu-advantage enable-esm $LEGACY_TOKEN

echo "Check policy of esm package apport"
lxc exec sru-precise -- apt-cache policy apport

echo "Attempt download of apport"
lxc exec sru-precise -- apt-get install -d apport

#lxc exec sru-precise /add_uat_apt_pocket.sh devel  # point to ua-tools PPA

#echo -e "[Sources]\nAllowThirdParty=yes" > allow.cfg
#lxc file push allow.cfg sru-precise/
#lxc exec sru-precise -- mkdir -p /etc/update-manager/release-upgrades.d
#lxc exec sru-precise -- mv allow.cfg /etc/update-manager/release-upgrades.d

echo "Dist-upgrade precise -> trusty"
VM_IP=`lxc list sru-precise -c 4 | awk '/10/{print $2}'`
echo "Upgrading to trusty via do-release-upgrade"
ssh ubuntu@$VM_IP 
# sudo do-release-upgrade # respond yes to any interactive prompts
# exit from ssh session

lxc exec sru-precise -- grep VERSION_ID /etc/os-release

echo "Check trusty policy of esm package krb5-user"
lxc exec sru-precise -- apt-cache policy krb5-user

echo "Attempt trusty download of krb5-user"
lxc exec sru-precise -- apt-get install -d krb5-user

mkdir -p precise-esm-dist-upgrade-pre-proposed
lxc exec sru-precise -- find / -xdev | sort > precise-esm-dist-upgrade-pre-proposed/files.list
lxc file pull -r sru-precise/etc precise-esm-dist-upgrade-pre-proposed/

echo "Upgrade to -proposed ua-tools"
lxc exec sru-precise /add_uat_apt_pocket.sh devel  # point to ua-tools PPA
lxc exec sru-precise -- apt-get update -q
lxc exec sru-precise -- apt-get install -qy ubuntu-advantage-tools

mkdir -p precise-esm-dist-upgrade-post-proposed
lxc exec sru-precise -- find / -xdev | sort > precise-esm-dist-upgrade-post-proposed/files.list
lxc file pull -r sru-precise/etc precise-esm-dist-upgrade-post-proposed/

echo "Part 2: Restoring pristine precise without esm enabled"
lxc restore sru-precise sru-precise-pristine

echo "Enable esm on precise"
lxc exec sru-precise ubuntu-advantage enable-esm $LEGACY_TOKEN

echo "Upgrading to trusty via dist-upgrade"
lxc exec sru-precise -- sed -r -i 's,precise,trusty,' /etc/apt/sources.list
lxc exec sru-precise -- sed -r -i 's,^(deb https.*)precise main,\1trusty-updates main\n\1trusty-security main,' /etc/apt/sources.list.d/ubuntu-esm-precise.list
lxc exec sru-precise apt-get update
lxc exec sru-precise -- apt-get dist-upgrade -y --force-yes

**Pull request merged**
