### PR TITLE
Refactor messages wording

### PR DESCRIPTION
**Pull request by mm-cr**
## Why is this needed?
This change adjusts messages for consistency, using the 'attach/detach/enable/disable' correct usage for the 'subscription' and 'service' terms.

Fixes: #2788

## Checklist

 - [x] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any integration tests accordingly
 - [ ] Changes here need to be documented, and this was done in: 

## Does this PR require extra reviews?

 - [ ] Yes
 - [x] No @orndorffgrant could you please take a look?

### CODE REVIEW

**Review by orndorffgrant — COMMENTED** [review]
These changes look great @mm-cr! Thanks for finding all of these instances of that issue.

Just a couple small things to get this PR ready to merge.
1. We have release-tooling that will grab fixed issues from commit messages, but it will only work if they're formatted in a particular way. Please change the line in your commit from `fixes issue #2788` to `Fixes: #2788`
2. This updates translatable messages, so please run `./tools/update-pos.sh` which will update the translation files.

Then I'll click the button to let CI run. Some of them may fail since they expect a branch rather than a fork, but I expect the important ones to pass.

After that, since some of these messages are already translated to pt_BR, we'll ask @lucasmoura or @renanrodrigo to update those translations.

**Comment by mm-cr** [comment]
Ready! Please @orndorffgrant let me know if anything else is needed.

**Review by orndorffgrant — APPROVED** [review]
Thanks for the contribution @mm-cr! I'll go ahead and merge this.

@lucasmoura and @renanrodrigo how do you want to handle updating translations? We could do it right away in a separate PR, or we could wait until release time and then update all `fuzzy` translations before releasing WDYT?

**Comment by orndorffgrant** [comment]
Created #2877

**Pull request merged**
